### ISSUE TITLE
[Solved] Kubernetes SVC Duplicate Configuration Causing Pod Connectivity Issues

### ISSUE THREAD

**Issue by songinyong** [SmartX-Team/OpenARK#4]
문제: 한 Service(LoadBalancer)가 의도치 않게 여러 PostgreSQL Pod를 대상으로 설정되어, 하나의 IP로 여러 DB 인스턴스가 노출되면서 연결이 간헐적으로 끊기고 인증 오류 발생.

원인: 

두 개 이상의 PostgreSQL Pod가 name-twin 에 배포되어 있었는데,
서로 그룹이 각각 다른 PostgreSQL Pod 를 배포했지만 Selector(label) 이름이 동일했음.

해결:
Deployment 와 SVC의 Label 들을 고유하게 변경
Service Selector 가 특정 PostgreSQL Pod만 선택

추가 권장사항:
MobileX Cluster 내 네이밍 컨벤션/Selector 중복 검증
배포 전 Endpoints 모니터링

문제 증상:

PostgreSQL LoadBalancer IP로 접속 시 간헐적인 연결 문제 발생(Pod 자체는 항상 Running 상태 유지)
Pod 상태는 정상이나, 클라이언트 연결이 불안정(연결 시도 시 비정상적으로 긴 Timeout이 발생)

-당시 인증 오류 메시지 출력-

connection to server at "10.80.0.2", port 5432 failed: FATAL: password authentication failed for user "myuser"
하지만 credentials로 연속적으로 3~4회 재시도 시 정상 연결되는 증상이 지속적으로 발생

문제 해결을 위해 꽤 많은 시간을 사용했는데, 최종적으로 위와 같이 Label 이름 충돌로 인한 문제였던걸로 확인됨

**Issue:** A Service (LoadBalancer) was unintentionally configured to target multiple PostgreSQL Pods, exposing multiple DB instances through a single IP, resulting in intermittent connection drops and authentication errors.

**Root Cause:**
Multiple PostgreSQL Pods were deployed on name-twin,
Different groups deployed separate PostgreSQL Pods but used identical Selector (label) names.

**Resolution:**

Changed Deployment and SVC Labels to be unique
Modified Service Selector to target specific PostgreSQL Pod only

**Additional Recommendations:**

Validate naming conventions/Selector duplications within MobileX Cluster
Monitor Endpoints before deployment

**Detailed Description:**

Intermittent connection issues when accessing PostgreSQL LoadBalancer IP
Pods were healthy, but client connections were unstable (abnormally long timeouts during connection attempts)

**Authentication error message output:**
"connection to server at "10.80.0.2", port 5432 failed: FATAL: password authentication failed for user "myuser""
Intermittent behavior where normal connection was established after 3-4 retries with the same credentials
Pods consistently maintained Running status
Considerable time was spent troubleshooting, ultimately confirmed to be caused by Label name conflicts as described above

**Comment by HoKim98** [comment]
Deployment와 Service 라벨링은 수동 지정하는 것이 맞습니다.

추가로 Affinity 설정을 통해 DB Pods를 특정 노드 그룹에 할당할 수 있습니다.
이를 지정하지 않으면 MobileX Stations 에 Pod가 배포될 수 있고 이에 따른 접속 불안정을 겪을 수 있습니다.

```yaml
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
            - key: node-role.kubernetes.io/kiss
              operator: In
              values:
                - Storage
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/kiss
              operator: In
              values:
                - Compute
                - Storage
```
